### ISSUE TITLE
disableLogger is evil

### ISSUE THREAD

**Issue by mgroth0** [DragonKnightOfBreeze/Paradox-Language-Support#100]
I just spent the last 6 hours figuring out why `System.out.println()` was not working in my IntelliJ plugin. First, I spent hours trying to figure out "why my plugin was not starting". But it turns out the whole time it was, and that printing was just not working. Eventually I went through all of my plugins and disabled them in batches and then one by one and finally isolated this plugin as being the singular cause of my issue. I had a hunch that there would be something weird in here, but then I saw `disableLogger`. This is not just weird, this is evil. This has devestating global side effects which create _silent_ issues for every other plugin, the kind that make people have to spend 6 hours on a saturday debugging. Please never modify the global logger in production code especially on a JVM that is shared with others.

**Comment by DragonKnightOfBreeze** [comment]
Sorry, I will make it configurable and by default disabled next version.
