### ISSUE TITLE
Victoria 3 link Comparisons

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#101]
Hi I think a CWT extension is needed here:

In Victoria 3 scripts you can use a link to get value comparision with another scope.

This gets the number of trade route levels with another country:
`num_mutual_trade_route_levels_with_country(root)`

This gets the relations number between the in scope country and actor:
`relations(scope:actor)`

This format is also used in Victoria 3 scripts, which seems to be the same as above:
`relations:root`

to define something like this in links would need something like:
```
relations = {
    input_compare_scopes = country
    input_scopes = country
    output_scope = value
    type = value
}
```

The idea is when input_compare_scopes is set the following things would then be valid:
`relations:root`
`relations:prev`
`relations(c:PRU)` scope of prussia
`relations(scope:actor)` some scope that is defined for the context

**Comment by DragonKnightOfBreeze** [comment]
Not quite understand how to impelement, may be manually checked and debugged later...

**Comment by DragonKnightOfBreeze** [comment]
1. Is `output_scope` and `input_compare_scopes` not always the same
2. Can `input_compare_scopes` be multiple?
3. Is `x` in `relations(x)` a scope field expression (just like common `root.owner.event_target:xxx`), nested in the whole expression `relations(x)`

**Comment by kaiser-chris** [comment]
If you look at this pull request it shows a few examples I defined for test purposes. Maybe that can help with understanding:
https://github.com/kaiser-chris/cwtools-vic3-config/commit/afcf0f95b4dc336d823bb19a259ab3c5f180d99f

To your questions:
1. `output_scope` and `input_compare_scopes` should generally be different. If you look at the example I provided with relations, the `output_scope` is value since a number is returned after the comparision.
2. Maybe? I have not found any examples in the base game but I could easily construct/think of things where this could be possible in the future the same way where a value field can have multiple `input_scopes` already.
3. `relations(x)` is not a scope expression but a value expression because what it does is take the country that is in scope (this) and gets its relations with another country x. You get the value of something.

Just maybe to clarify and provide a further example. Let us look at `scripted_bar_progress`.
What does it do:

- For a journal entry that is in scope (this = some journal entry) it gets the progress of a scipted progress bar.
- Existing CWT Type for Journal Entry: common/scripted_progress_bars.cwt
- Existing CWT Type for Scripted Progress Bar: common/journal_entries.cwt

Here is an example how it is used in a base game file trigger:
```
... more code before
	fail = {
		custom_tooltip = {
			text = communism_progress_bar_at_full_tt
			scope:journal_entry = {
				"scripted_bar_progress(communism_1_progress_bar)" >= 100
			}
		}
	}
... more code after
```

An example how I would configure it in CWT (This is just an idea and example):
```
scripted_bar_progress = {
    compare_from_data = yes # Not in current CWT standard
    compare_data_source = <scripted_progress_bar> # Not in current CWT standard
    input_scopes = journal_entry
    output_scope = value
    type = value
}
```

**Comment by DragonKnightOfBreeze** [comment]
There are various (and more) 'complex' expressions in paradox script&loc files, 
and so do plugin's codes.
I once thought the implementation for complex expressions is not so good, 
but currently, luckly, it's still not very hard to implement those language features.

**Comment by kaiser-chris** [comment]
Just one more example I found:
![image](https://github.com/user-attachments/assets/1af4f358-c025-4d30-bf7f-e5f95b49e441)

Seems like scope chaining can also happen in there.

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/user-attachments/assets/6f743dea-a49c-4da1-b0e4-09a26cfe2b4a)

Is this correct and necessary?
I have no idea to differ and match these two configs exactly yet.

**Comment by kaiser-chris** [comment]
Hmm I think only the arithmetic one is needed.

But I am not 100% sure. I am currently not at home to search the base game files for it.

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/user-attachments/assets/9a2450f2-56e7-4932-b879-f0b53e24761a)

`relations:xxx`

This is missing in cwt configs

**Comment by DragonKnightOfBreeze** [comment]
> Hi I think a CWT extension is needed here:
> 
> In Victoria 3 scripts you can use a link to get value comparision with another scope.
> 
> This gets the number of trade route levels with another country: `num_mutual_trade_route_levels_with_country(root)`
> 
> This gets the relations number between the in scope country and actor: `relations(scope:actor)`
> 
> This format is also used in Victoria 3 scripts, which seems to be the same as above: `relations:root`
> 
> to define something like this in links would need something like:
> 
> ```
> relations = {
>     input_compare_scopes = country
>     input_scopes = country
>     output_scope = value
>     type = value
> }
> ```
> 
> The idea is when input_compare_scopes is set the following things would then be valid: `relations:root` `relations:prev` `relations(c:PRU)` scope of prussia `relations(scope:actor)` some scope that is defined for the context

For this, `relations:root` and `relations(root)` shall be all valid and same,
and `input_scopes` and `input compare_scopes` should be same,
for you cannot use `:` to separate prefix `relations` and dynamic scope link `c:PRU`.
so, it may be just a alias format if `datasource = scope_field` or `datasource = scope[country]`, etc.

**Comment by DragonKnightOfBreeze** [comment]
And, it should be only valid and avaiable for value_field (`ParadoxValueFieldExpression`, in plugin code)

**Comment by DragonKnightOfBreeze** [comment]
fyi nearly implemented

**Comment by DragonKnightOfBreeze** [comment]
There still are some bugs and unimplemented features, like the validation for data source type `scope[country]`

**Comment by DragonKnightOfBreeze** [comment]
@kaiser-chris  Since now you can create the PR for `from_argument` link configs :)

**Comment by DragonKnightOfBreeze** [comment]
Paradox-Language-Support-1.3.26.zip

**Comment by kaiser-chris** [comment]
> @kaiser-chris Since now you can create the PR for `from_argument` link configs :)

Would love to but I will be unable to until late next week since I am currently traveling.

But thank you already this looks good but does it also support things like the scripted_bar_progress I have written about above or is that part still missing?

**Comment by kaiser-chris** [comment]
> If you look at this pull request it shows a few examples I defined for test purposes. Maybe that can help with understanding: [kaiser-chris/cwtools-vic3-config@afcf0f9](https://github.com/kaiser-chris/cwtools-vic3-config/commit/afcf0f95b4dc336d823bb19a259ab3c5f180d99f)

If you want a few more test cases you can find almost all compare uses in the Commit I linked. I needed to remove them because they broke the original CWT tools but it still provides a comprehensive list of them.

Otherwise I will configure them myself in CWT late next week.

**Comment by DragonKnightOfBreeze** [comment]
I will seen them next week

**Comment by DragonKnightOfBreeze** [comment]
@kaiser-chris If what you said is that, for `populist_unrest_progress_bar` in  `scripted_bar_progress(populist_unrest_progress_bar)`, it's a definition (a progress bar), not a scope field expression (like `root.owenr`), it should be also supported.

**Comment by kaiser-chris** [comment]
Thank you that's correct.  I will be back home on Thursday and start working on that.

**Comment by kaiser-chris** [comment]
Thank you that's correct.  I will be back home on Thursday and start working on that.

**Comment by DragonKnightOfBreeze** [comment]
Hi @kaiser-chris I just made some optimizations for `links.cwt` of vic3 config, there should be further check and opitmization, since I found some links are missing, and some datasource type are not checked yet. I will release plugin version 1.3.26 later.

**Comment by kaiser-chris** [comment]
Hi @DragonKnightOfBreeze I am back and currently implementing the links with the provided plugin version.

Generally it works but this construct does not seem to work.

Usage:
![image](https://github.com/user-attachments/assets/5cb4cdb1-cf24-4792-897f-62c5ba3eed7e)

My CWT definition:
```
### Check whether another country has a diplomatic pact of this type with given country
diplomatic_pact_other_country = {
    desc = "Check whether another country has a diplomatic pact of this type with given country"
    type = scope
    from_data = yes
    from_argument = yes
    prefix = diplomatic_pact_other_country:
    data_source = scope[country]
    input_scopes = { diplomatic_pact }
    output_scope = country
}
```

**Comment by DragonKnightOfBreeze** [comment]
with quotes?

**Comment by kaiser-chris** [comment]
Yes these comparisions are often used with quotes in the base game files.
For value stuff it works but this one does not work.
I think the issue is that the output is not a value but a scope.

**Comment by DragonKnightOfBreeze** [comment]
with quotes should be allowed due to my validation.
what's the error message?

**Comment by kaiser-chris** [comment]
Error:
![image](https://github.com/user-attachments/assets/8a0a4850-3fd3-4936-9852-1160923ef2dc)

This should resolve as a trigger because there is this in scope_links.cwt:
![image](https://github.com/user-attachments/assets/d173b16b-d5ba-429d-807e-a302d09ef76c)

**Comment by DragonKnightOfBreeze** [comment]
Seems that `diplomatic_pact_other_country(root)` is a scope link (rather than value field) which is not 
specially handled

**Comment by DragonKnightOfBreeze** [comment]
Handled, but there are still some other problems in vic3 game files, will be checked in futher plugin versions

**Comment by kaiser-chris** [comment]
Thank you for all your hard work.
I will look for further errors and report what I find.
