### ISSUE TITLE
Support using inline math block as scripted variable value

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#108]
Hi @DragonKnightOfBreeze,

I found another one in Victoria 3.
Advanced @ variables seem to break parsing:
![image](https://github.com/user-attachments/assets/ef6ff244-72a5-4138-8b1b-39d2537fbfa8)
![image](https://github.com/user-attachments/assets/443ba250-f929-4f6b-84f3-bc4928576702)
![image](https://github.com/user-attachments/assets/f6a5188c-867c-456f-bde4-2966cb93f727)

The first example is from a gui file and the second is from a coat of arms base game file.

How these advanced @ variables work:

- Contain calculations (Found plus, minus, multiply and divide)
- Other @ variables can be referenced without using @ before it (See first example above)
- Can contain absolute values (See second example above)
- Can be used in place of values (See third example above)

_Originally posted by @kaiser-chris in https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/issues/102#issuecomment-2522770203_

**Comment by DragonKnightOfBreeze** [comment]
So such syntax is possible and allowed...

**Comment by DragonKnightOfBreeze** [comment]
And, so scripted variable in such syntax, cannot be recursive, another inspection is necessary.

**Comment by DragonKnightOfBreeze** [comment]
5da8ab245c68f7f4500db7236f05cd0adadcfde0
Shall be supported in 1.2.1, should be checked again.

**Comment by DragonKnightOfBreeze** [comment]
[Paradox-Language-Support-1.3.27.zip](https://github.com/user-attachments/files/18071594/Paradox-Language-Support-1.3.27.zip)

**Comment by kaiser-chris** [comment]
It now works but there seems to be a problem with recognicing references:
![image](https://github.com/user-attachments/assets/819e2d84-d5b9-4136-a44f-611610f85598)

**Comment by DragonKnightOfBreeze** [comment]
Will fix it soon

**Comment by DragonKnightOfBreeze** [comment]
[Paradox-Language-Support-1.3.27.zip](https://github.com/user-attachments/files/18074909/Paradox-Language-Support-1.3.27.zip)

**Comment by kaiser-chris** [comment]
Works like a charm:
![image](https://github.com/user-attachments/assets/619358b7-18b9-4188-a49d-0e7fb133d3e5)

Thank you!
