### ISSUE TITLE
只能读取动态肖像而不能读取静态肖像

### ISSUE THREAD

**Issue by Outofamazement** [DragonKnightOfBreeze/Paradox-Language-Support#13]
![2023-03-29 10 12 08](https://user-images.githubusercontent.com/47137766/228408769-d607c95f-d8d2-4ad2-a813-4e16a031fe00.png)

强制要求attach_selector、clothe_selector等动态肖像特有的键，无法识别静态肖像。

**Comment by DragonKnightOfBreeze** [comment]
将在0.9.4（IDEA版本2023.1）修复
