### ISSUE TITLE
stellaris颜色模板还是没法用

### ISSUE THREAD

**Issue by Snowon-I** [DragonKnightOfBreeze/Paradox-Language-Support#18]
即便在意图中的change color已经是打了√，但是在本地化中还是不会弹出选框，不知道是我的问题，还是什么，我尝试重装一遍

**Comment by Snowon-I** [comment]
是不是我对更新日志的理解出了问题，是不是已经移除了在选取本地化文件时弹出颜色选框，转而将这个功能移动到了代码的包围里面......

**Comment by DragonKnightOfBreeze** [comment]
1. 意图中的change color（放到color id上可用）和选择本地化文本出现颜色悬浮工具栏不是一个功能
2. 更新日志中是说对后一个版本做了优化，现在看来有点bug

**Comment by Snowon-I** [comment]
好的，谢谢作者答复
