### ISSUE TITLE
新版本事件代码检测BUG

### ISSUE THREAD

**Issue by Snowon-I** [DragonKnightOfBreeze/Paradox-Language-Support#22]
群星（新版本，上个版本没有这个问题）
在event的文件中，不管哪个event，在有了hide_window = yes后，title是不必要的，同时也不是每个event都需要base = 
但是却在定义中会存在报错
Missing key expression 'base' (expecting at least 1, actual 0) 
Reports expressions that are missing in definition declarations.

Missing key expression 'title' (expecting at least 1, actual 0) 
Reports expressions that are missing in definition declarations.

**Comment by Snowon-I** [comment]
![p1](https://user-images.githubusercontent.com/129295383/233669051-c697fbd0-6b17-4f8e-b087-e7df6e93b176.png)
![p2](https://user-images.githubusercontent.com/129295383/233669082-599ab458-531c-47c9-b489-f73deccaafae.png)

**Comment by DragonKnightOfBreeze** [comment]
还有这种新bug？明天看看。

**Comment by DragonKnightOfBreeze** [comment]
卧槽，某个地方忘记实现代码了

**Comment by DragonKnightOfBreeze** [comment]
59b6fbc77e5cc0a42452e6e2b395ac33a243619e
