### ISSUE TITLE
.${gameType} file is ignored

### ISSUE THREAD

**Issue by toliner** [DragonKnightOfBreeze/Paradox-Language-Support#3]
I'm doing HoI4 modding with this plugin, however, the plugin mark the mod as Stellaris's one.

Project Directory
![image](https://user-images.githubusercontent.com/33022206/174296103-a1e8590f-b71a-4342-9952-0595faf3ffc3.png)
Project is recognized as Stellaris mod
![image](https://user-images.githubusercontent.com/33022206/174296306-44a3220a-1c1f-4f38-99a7-0619a452bef5.png)

**Comment by DragonKnightOfBreeze** [comment]
I suggest to use VSCode with CWTools until I implement CWT Config File Support more perfectly.
Bug feedback is always welcomed.

**Comment by DragonKnightOfBreeze** [comment]
THX!

**Comment by DragonKnightOfBreeze** [comment]
47ca26ad471d329131add82353581cb6962d29dc
