### ISSUE TITLE
Conditional [[param]...] in scripted_triggers/effects/values have highlight issues when incorporated with prefixes/suffices

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#30]
As title says, using conditional with params inside metascripts with prefixes and suffixes causes highlight issues.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/a61c8fca-28e9-4f72-8761-41c4e8cb616e)

**Comment by DragonKnightOfBreeze** [comment]
Not plan to support yet. Be more kind, and less foxy, plz.

**Comment by DragonKnightOfBreeze** [comment]
Are u similar with kotlin and Intellij platform?

**Comment by DragonKnightOfBreeze** [comment]
If u are pleasure, you can try to complete and optimize these CWT configs for Stellaris (it should be very perfect now) and other Paradox Games. try checkout these CWT config repos of mine forked from cwtools'.

**Comment by adriangaro** [comment]
I am familiar with Kotlin, not so much with writing Intellij plugins x3 But when i will have some try will try the repo locally and see how the innards work and see if I could contribute to some minial amount at least, hah!

**Comment by DragonKnightOfBreeze** [comment]
Is `aaa[[bbb] ccc ]ddd` valid? (Notice the white space around `ccc`)
Is `"aaa[[bbb] ccc ]ddd"` valid? (Notice the double quote around)

**Comment by adriangaro** [comment]
I think the spaces are not valid as they would add spaces within the thing you want to insert the conditional text.

I think the metascript is basically evaluated at load time and does the substitutions with the parameters, whitespace included

I know that i use some tricks for inline scripts to disable some code by making some parameters # which basically transform the line into a comment for example. So my guess is that whitespace would be inserted if you have whitespace within the square brackets.

Can do a quick test tomorrow and report back.

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/9b3db9e6-f2ac-47bb-b6f5-7664d1a667b1)

**Comment by DragonKnightOfBreeze** [comment]
Will be optimized in 1.1.11
