### ISSUE TITLE
Ctrl+1 does not work in some inspections related to inline scripts.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#34]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/aade9efd-a945-4f05-803b-3a2548850937)

Pressing `Ctrl+1` does nothing in the above inspection, wanted to see what the conflicting scopes were.

**Comment by DragonKnightOfBreeze** [comment]
It's not supposed to be shown what the conflicts are so far, maybe you can provide a template to show the details.
