### ISSUE TITLE
Scripted variable should be valid tokens for script values parameters

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#37]
As title implies, scripted variables can be passed to script values as parameters. (sorry again for poking at this stuff >.<)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/4ef81883-6faa-4051-b88a-fd4e984e9266)

**Comment by DragonKnightOfBreeze** [comment]
WTF?

**Comment by DragonKnightOfBreeze** [comment]
Allowed and resolved since 1.1.3 (Implemented by Language Injection).
