### ISSUE TITLE
Cyan color support in localisation

### ISSUE THREAD

**Issue by toliner** [DragonKnightOfBreeze/Paradox-Language-Support#4]
(at least) in HoI4, Cyan color is supported with id "C", however, this plugin say it as invalid.
Full reference for HoI4 color ids are here: https://hoi4.paradoxwikis.com/Localisation

**Comment by DragonKnightOfBreeze** [comment]
Currently this plugin resolve localisation colors (for ALL Paradox Games) by config/internal/localisation_config.pls.cwt

**Comment by toliner** [comment]
Thank you for your reply!

in HoI4, `textcolors` is written in `interface/core.gfx`, so other Paradox games may defined in other files :(
![image](https://user-images.githubusercontent.com/33022206/174310439-307869ea-d160-45e8-86a5-2427f7d98fd7.png)

**Comment by DragonKnightOfBreeze** [comment]
Should modify original cwt rule files to support it. Hard to write codes. (⊙︿⊙)

**Comment by DragonKnightOfBreeze** [comment]
7bdac41e3956d9d84a54d8aeb3e2ae1b59c775f2
