### ISSUE TITLE
Non necessary localization is marked as missing for thing marked with `is_capped_by_modifier = no`

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#40]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/457835b8-8581-4cb8-834c-5952dfcf4a32)

**Comment by DragonKnightOfBreeze** [comment]
https://github.com/DragonKnightOfBreeze/cwtools-stellaris-config/commit/184d79fe1c253282d8127920c588b11e36f23bcd
