### ISSUE TITLE
Generate all missing localisation for jobs should generate the locs for autogenerated modifiers too

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#41]
Would be neat if it would be possible, it would remove a lot of copy pasting. Also generating and `effect_desc` would be lovely too.

**Comment by DragonKnightOfBreeze** [comment]
organization -> localisation ?

**Comment by adriangaro** [comment]
Yeah typo XD, was in a meeting while making the ticket and i think the word slipped in xd

**Comment by DragonKnightOfBreeze** [comment]
Note that the cwt configs are updated, and some locs are optional, not inspected and generated by default.

**Comment by adriangaro** [comment]
Very fair, could there be an option to generate the optional ones too?

**Comment by DragonKnightOfBreeze** [comment]
Will be optimized in v1.1.5

**Comment by DragonKnightOfBreeze** [comment]
![1691009594235~1](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/170be9b8-1b86-49c9-a057-6d30349cc67c)
