### ISSUE TITLE
council_demand property is missing from cwt tools config

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#42]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/79292afb-89cd-4f92-b537-8c3325d02b46)

This is from the vanilla inline `paragon/global_faction_demands.txt`

**Comment by DragonKnightOfBreeze** [comment]
https://github.com/DragonKnightOfBreeze/cwtools-stellaris-config/commit/d861d78293f568dea46ec996df7e7e46f86d8bb0
