### ISSUE TITLE
Renaming a scripted modifier does not change the localizaiton key name

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#43]

**Comment by DragonKnightOfBreeze** [comment]
![1691009594235~1](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/170be9b8-1b86-49c9-a057-6d30349cc67c)

**Comment by DragonKnightOfBreeze** [comment]
Will be optimized at 1.0.7
