### ISSUE TITLE
Ascension Perks allows tradition swaps, plugin recognizes them but no syntax highlighting

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#44]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/3a88faa6-e067-4b5f-9ca3-76743cd88e8c)

Ascension perks are technically traditions behind the scenes, and allow `tradition_swaps` (used in vanilla for Enigmatic Engineering)

**Comment by DragonKnightOfBreeze** [comment]
If you found an issue is only cwt related, aka, can be resolved just by modify some cwt configs (See my folks of cwt configs), you can try to send a PR to that repo.
