### ISSUE TITLE
Parameter of type scope in scripted effects breaks highlighting/does not get inferred by what is passed 

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#45]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/3efcce38-a622-4158-a20a-b2b464b948bc)

`$from$` is a scope here passed so i can be easily passed and changed to correct scope. syntax highlighting breaks inside it.

**Comment by DragonKnightOfBreeze** [comment]
The logic to get the CWT config of $from$ is to be determined.

**Comment by adriangaro** [comment]
Well yes, but in this case `$from$` is a parameter, not the scope `from` so it could be whatever is passed as to said parameter.

**Comment by DragonKnightOfBreeze** [comment]
We CANNOT get the actual config context in `$from$ = {...}` because `$from$` can be anything, and I think it's unsuitable to infer what `$from$` can be by checking all it's usages, to get the inferred config context.

**Comment by adriangaro** [comment]
Not necessarily to infer the scope type, but mostly fix the highlighting inside it, since no highlighting, nor autocomplete works inside the brackets.

**Comment by DragonKnightOfBreeze** [comment]
Shall be reselved by inference from custom cwt configs, but never from usages.
