### ISSUE TITLE
[1.1.4] Parameters with defaults passed to script values cause highlight errors.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#47]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/779143c5-f7b8-40d5-afa0-ee1e9735de11)

tested 1.1.4 and there seem to be a regression on parameters with defaults

**Comment by DragonKnightOfBreeze** [comment]
stupid force push...
