### ISSUE TITLE
[1.1.5] IDE freezes sometimes when loading autocomplete/intellisense for localization

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#48]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/8d6c8ba4-69f7-488f-b00d-60ec3f61e1ca)
Stays like this, prior to 1.1.5 the IDE still froze but had another popup waiting for the threads and usually would unfreeze at the end.

**Comment by adriangaro** [comment]
CPU usage is at 0% when the IDE freezes this way.

**Comment by DragonKnightOfBreeze** [comment]
Kill IDE and restart to get the IDE error log, then put it here.

**Comment by DragonKnightOfBreeze** [comment]
Hmmm...the IDE error log may not be easy to get. 
Should profiling and check plugin code later at 1.1.6.

**Comment by DragonKnightOfBreeze** [comment]
Tested at 1.1.6 after some optimization, shold not be a very serious performance problem.

**Comment by DragonKnightOfBreeze** [comment]
It's optimized but I met a IDE freeze during debugging sometimes, if you meet it after 1.1.6 is published, create another issue.
