### ISSUE TITLE
Job modifiers inherit icons in game, but are marked as missing by plugin

### ISSUE THREAD

**Issue by TTFTCUTS** [DragonKnightOfBreeze/Paradox-Language-Support#50]
A possible enhancement: 

Some modifiers such as `job_<x>_add`, where the corresponding job has an `icon` field set, use the icon corresponding to the name set in the field instead of the job's name.

Currently, the plugin will complain that the icon matching the modifier's name is missing, but this relation could potentially be inferred.

An example:

Here, the Iodizium Mining Drone has its icon set to the Iodizium Miner job, and in game the drone modifier uses the icon for `job_giga_iodizium_miner_add`. 
The plugin warns that the icon matching the modifier name is missing, which is true, but that's not the icon which the game ultimately uses. It could potentially infer the relation from the job and use the other icon like it does in game.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/d9157b0e-b81b-4eaa-8907-9465583a3dc6)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/60972e5f-1206-4e5b-8338-bf33012f4d97)

As always, great work with the plugin, it helps our development work tremendously. Thank you for your efforts.

**Comment by DragonKnightOfBreeze** [comment]
So the logic to get the actual modifier icon path should be optimized.
And it seems like there are some other 'inherit icons' situations.

**Comment by DragonKnightOfBreeze** [comment]
Plugin now simply get the modifier icon path by template expression "gfx/interface/icons/modifiers/$.dds"， where "$" is the modifier name.

It seems like there should be some addtional inference logic (and are there others?),
and the icon file could also be a png file.

**Comment by TTFTCUTS** [comment]
Some others:
- Economic category modifiers use icons related to their resources (there's some nuance to this one, worth careful investigation, particularly for modifiers which don't point at a specific resource)
- Scripted modifiers can specify an icon in their definition.

All of these (note the warnings in the scroll bar) have icons in-game
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/2dc72bec-c219-4041-bdc8-d18417c4a617)

**Comment by DragonKnightOfBreeze** [comment]
![B6GOJTV~EQF@1I1DU`XQABR](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/4ec915b5-d1b4-46cb-bf90-957f806110dd)

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/bb530b8f-dcb1-4e37-a186-7d4e85987a9d)

**Comment by DragonKnightOfBreeze** [comment]
Not sure what's the icon generation rule for template-based modifier (e.g. `shipsize_<ship_size>_build_speed_mult`).
