### ISSUE TITLE
无法解析使用了scripted_variables的参数预设值

### ISSUE THREAD

**Issue by Elivicti** [DragonKnightOfBreeze/Paradox-Language-Support#51]
在`script_value`和`scripted_effect`里使用`scripted_variables`作为参数的预设值会报错

<img width="588" alt="Snipaste_2023-09-21_17-25-11" src="https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/50987873/ea0f10c4-bd20-4ac9-8df5-5a2297a5a450">

其中`@GF_zion_project_energy_cost_1`为定义在`scripted_variables`里的常量，值为5000

经测试，游戏内使用如下代码会将变量的值设为5000，所以代码是有效的
~~~
set_variable = {
    which = v_test
    value = value:GF_test|VALUE|7500|
}
~~~

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/8ec617b5-aa06-4d15-9ec5-72f6453f2ff6)
