### ISSUE TITLE
Event Files for CK3 are broken, syntax is not understood

### ISSUE THREAD

**Issue by MrFunEGUY** [DragonKnightOfBreeze/Paradox-Language-Support#52]
Basically every single line of every single CK3 event file is underlined with errors because it seems the plugin cannot understand how event files in CK3 are coded.

**Comment by alexei-osipov** [comment]
It looks like only files for mods have issues. Main game files are mostly fine with few exceptions.

For example, the new comparison operator `?=` is not recognized:
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/8040900/05609ea2-b370-47a1-8341-1a8afdab7192)

**Comment by DragonKnightOfBreeze** [comment]
What's your plugin version ? `?=` should be valid syntax now (but invalid during to inspection `IncorrectSyntaxInspection`)

**Comment by kaiser-chris** [comment]
@DragonKnightOfBreeze I think this issue should be fixed as well because of your fix for #86.
