### ISSUE TITLE
Support for Database Concepts

### ISSUE THREAD

**Issue by TTFTCUTS** [DragonKnightOfBreeze/Paradox-Language-Support#56]
As detailed in `common/game_concepts/99_README_CONCEPTS.txt`, concepts are now auto-generated from several different types of database object. Concepts of this format are currently unsupported by the plugin.

Not disruptive at all, but I figured you'd want to know.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/db048e64-7f21-489b-892f-a24652be3772)

**Comment by DragonKnightOfBreeze** [comment]
Will be supported basicly in 1.3.13
