### ISSUE TITLE
Parameters of inlines show as unused if they cannot be inferred correctly even if declared in cwt config.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#64]
Parameters of inlines show as unused if they cannot be inferred correctly even if declared in cwt config.

Inline definition
```
# conditional/tec_bool
inline_script = {
	script = conditional/parts/tec_bool_$value$
	code = '
		$code$
	'
}
```

Cwt parameter definitions
```
    ### conditional/tec_bool
    ## context_key = inline_script@conditional/tec_bool
    value = bool
    ## context_key = inline_script@conditional/tec_bool
    ## context_configs_type = multiple
    code = {

    }
```

Usage
```
inline_script = {
    script = conditional/tec_bool
    value = yes
    code = '
        inline_script = {
          script = inline_included_if_value_is_true
          trigger = " is_gestalt = yes "
    '
}
```

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/51bb7415-8c92-4287-9b25-2e3a20dd6532)

As it can be seen the `value` parameter is shown as unused, and when trying to autocomplete it, the IDE does not suggest it. Same with `code`

This also might be tied to another bug i found that single counted strings are not accepted, while they do work for scripting purposes in general, the main use case is being able to pass double quoted strings as parameters since, escaping the quotes otherwise can cause issue downstream when the mod is loaded. Will create a separate bug for this too.

**Comment by adriangaro** [comment]
If a parameter is declared in the cwt config, ideally it should be considered used, if it has been intentionally declared there (even maybe if infering from the inline is impossible). It will help with cases where the logic might be too complex/niche and allow modders to overwrite those parameters and correct what cannot be inferred.

**Comment by DragonKnightOfBreeze** [comment]
Use 1.3.3 or pre-released 1.3.4?
The used or not inspection is implemented based on related indices. However in pre-released 1.3.4 parameter index is disabled due to IDE freezing problem. If you use 1.3.3, this shoulf be a index problem or inspection implementation problem.

**Comment by DragonKnightOfBreeze** [comment]
It's not desired to be based on CWT configs, same for other things. You can instead "Suppress or disable related inspections"

**Comment by adriangaro** [comment]
1.3.4 is used here, same behaviour was prior in 1.3.3 i think. But can check

**Comment by DragonKnightOfBreeze** [comment]
So it is, plz ignore it since 1.3.4 is not fully updated.

**Comment by adriangaro** [comment]
Ok will do, thanks for the note, atm disabled the inspection, so that is a temporary good solution. Should I keep this open till 1.3.4 is fully realeased?

**Comment by DragonKnightOfBreeze** [comment]
Just let me check, update and then close this issue.
