### ISSUE TITLE
Cannot choose path for library using CK3

### ISSUE THREAD

**Issue by SeamusFD** [DragonKnightOfBreeze/Paradox-Language-Support#7]
![image](https://user-images.githubusercontent.com/6413824/208508408-292500d9-f66f-4f7f-bbf1-542ec7fb7a67.png)
When adding a new library you cannot choose a valid game folder for ck3. Works with Stellaris but not the folder structure of ck3

**Comment by DragonKnightOfBreeze** [comment]
The logic to check whether a directory is a game directory should be optimized for other Paradox games.

**Comment by DragonKnightOfBreeze** [comment]
@SeamusFD 

I do not own CK3 in Steam and mainly test this plugin using Stellaris game directory and some mods. So:

Is there a json file named 'launcher-settings.json' under directory `game`, or it's parent directory `Crusader Kings III`?
If it exists, please send to me.

Is the exe file named `ck3.exe` and where is it located in?

**Comment by SeamusFD** [comment]
`{
	"gameId": "ck3",
	"displayName": "Crusader Kings III",
	"version": "1.8.1 (Robe)",
	"rawVersion": "1.8.1",
	"distPlatform": "steam",
	"gameDataPath": "%USER_DOCUMENTS%/Paradox Interactive/Crusader Kings III",
	"dlcPath": "../game",
	"ingameSettingsLayoutPath": "settings-layout.json",
	"themeFile": "./assets/theme-settings.json",
	"browserDlcUrl": "https://store.steampowered.com/dlc/1158310/",
	"browserModUrl": "https://steamcommunity.com/app/1158310/workshop/",
	"exePath": "../binaries/ck3.exe",
	"exeArgs": [ "-gdpr-compliant" ],
	"alternativeExecutables": [
		{
			"label": {
				"de": "Spiel im Debug-Modus öffnen",
				"en": "Open game in Debug Mode",
				"es": "Abrir juego en modo de depuración",
				"fr": "Ouvrir le jeu en mode débogage",
				"ja": "デバッグモードでゲームを開",
				"ko": "디버그 모드로 게임 열기",
				"pl": "Uruchom grę w trybie debugowania",
				"pt": "Abrir jogo em modo debug",
				"ru": "Запустить игру в режиме разработчика",
				"zh-hans": "以调试模式打开游戏",
				"zh-hant": "以調試模式打開遊戲",
				"tr": "Oyunu hata ayıklama modunda başlatın"
			},
			"exePath": "../binaries/ck3.exe",
			"exeArgs": [ "-gdpr-compliant","-debug_mode" ]
		}
	]
}
`
That is the launcher settings. And yes, it's path is in the exePath which is the Crusader Kings III/binaries/ck3.exe

**Comment by SeamusFD** [comment]
Also the project structure is like this
![image](https://user-images.githubusercontent.com/6413824/208701839-48028676-ab6a-48dd-9b57-08de84e778aa.png)
the game folder holds all the needed common, history etc folders

**Comment by DragonKnightOfBreeze** [comment]
So how tricky it is...
![image](https://user-images.githubusercontent.com/34092666/208702730-61329e0d-8096-4d40-9d69-2dbde9d1aac7.png)

**Comment by SeamusFD** [comment]
Yeah I would help with a PR but I cannot get the project to work anymore

**Comment by DragonKnightOfBreeze** [comment]
Paradox Language Support-0.7.8.zip

There is a hot fix.

**Comment by SeamusFD** [comment]
Very nice, when can I expect the new version?

**Comment by DragonKnightOfBreeze** [comment]
Hre is a preview (scope context inlay hints):

![image](https://user-images.githubusercontent.com/34092666/208720380-071c1e64-a945-4093-9fee-bb55e427fd00.png)

Also scope context quick documentation (should be different from CWTools).
