### ISSUE TITLE
Typing inline_script does not show autocomplete

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#70]
Could be useful to have an autocomplete snippet for it to easily write it, since most type you have to type `inline_script` manually, speeding up the insertion of inline scripts in most other places.

**Comment by DragonKnightOfBreeze** [comment]
So the question is 'What are the all available places', should it can be autocompleted everywhere in script files (in game/mod directory) when typing a proeprty key, or be limited?

**Comment by DragonKnightOfBreeze** [comment]
It's originally designed not to complete 'inline_script = ...', yet it may be coonfigured to complete.

**Comment by DragonKnightOfBreeze** [comment]
Will be implemented in 1.3.5
