### ISSUE TITLE
Some effects change root scopes

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#71]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/bc73695f-a789-443a-a566-198e713e5d93)

In this image we can see the effect scope is planet for both `this` and `root` but  `random_owned_pop` changes scope type of `root` to pop, instead of maintaining the previous `root` scope type. If anything no effect should change the scope of type of `root` and scripted effects with disjoint `root` scope should raise an error if they are mismatched.

Also `random_owned_pop` also changes scope of `prev` which should be `planet`, but the plugin sees it as `pop`, `random_owned_pop` changing this scope too, instead of changing it to previous scope.

**Comment by DragonKnightOfBreeze** [comment]
What's the actual `root` scope should `random_owned_pop` be?

**Comment by DragonKnightOfBreeze** [comment]
> If anything no effect should change the scope of type of root and scripted effects with disjoint root scope should raise an error if they are mismatched

And please give an example for this validation / inspection

**Comment by adriangaro** [comment]
As you can see near the top near the scripted trigger definition started, the scope for root is planet.

Root scope never changes to my knowledge during a trigger, regardless how many scope changes happen in rest.

The actual scope for root for `random_owned_pop` should remain unchanged and inherit the one from the place it was invoked then.

**Comment by DragonKnightOfBreeze** [comment]
Seems to be a code error, `## push_scope` is used in related configs and it should be right.

**Comment by DragonKnightOfBreeze** [comment]
Will be fixed in 1.3.6
