### ISSUE TITLE
Paramaters that are multi line trigger blocks do not type inference correctly.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#72]
I have this utility inline which forces usually the plugin to do type inference where it can't easily infer from the code due to complex use or if the parameter is used in interpolation. 

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/f36ef274-0da6-4833-970a-886e0440dbc9)
As you could see the parameter should try to make `$trigger$` into that specific `(complex)` (which is described in the cwt configs). 

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/046b807e-4559-4c6b-a780-fe9ca628b9c3)
However the type is lost due to having to put the parameter between quotes, as otherwise the trigger would bleed into the inline parameters invocation and cause errors at load time, so quotes are necessary.

I could think of two ways to handle this, one a shortcut which would fix in most cases, but not too versatile. It would be if something is simply just passed along with the quotes, to just copy the type of where it is passed as for inference purposed.

The second option would be to infer config/context from within the place where the parameter is interpolated/used.

For full context the snippet is bellow how `$trigger$` is used in the inline, and where type inference of it fails normally.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/91650bf8-0a45-455d-80b6-61c7466a1f34)

**Comment by DragonKnightOfBreeze** [comment]
What about related cwt configs and inline script files?

**Comment by DragonKnightOfBreeze** [comment]
Config of parameter `job_planet_trigger_block` is inferred from extended cwt configs
Config of parameter `trigger` is not inferred from extended cwt configs, and should be inferred from usages (based on paramerter `job_planet_trigger_block`)

Is above description right?

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/d7439aa5-0b7d-4167-9c7d-b5167ab3f8d4)

**Comment by DragonKnightOfBreeze** [comment]
May need further testing
