### ISSUE TITLE
Allow wildcard/template expression for parameter context_key

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#73]
Using * or `<job>` or `enum[my_enum]` in the `context_key` like in `context_key = inline_script@jobs/tec_*` does not work, would be great to allow it to easily be able to add parameter definition for inlines/effects/etc that respect a common interface.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/3afea09f-cc4a-43df-9c42-628b20d209de)

**Comment by DragonKnightOfBreeze** [comment]
Will be implemented in 1.3.6
