### ISSUE TITLE
Scripted effect not recognized, nor its cwt config.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#74]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/8bb306c0-80cb-4976-90a8-89a8dbb2f6bf)

`tec_cache` is an effect that is declared above with no errors, yet its invocation does not work and errors. The whole file seems to be affected as no scripted effect in it is recognized/autocompleted.

**Comment by adriangaro** [comment]
This issue seems to affect most of the project now, modifiers, scripted triggers and effects are not recognized, rebuilding the cache seems to have done nothing

**Comment by adriangaro** [comment]
Returning to 1.3.4 seems to fix this.

**Comment by DragonKnightOfBreeze** [comment]
Will be fixed in 1.3.6
