### ISSUE TITLE
Using `single_alias[trigger_clause]` in cwt extended definition parameters does not seem to work, nor using a multiple config type work as expected.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#76]
I have in many cases the need to pass a trigger block to an inline, and analyzing cwt configs there seem to be two ways of doing it, using `single_alias[trigger_clause]` like

```
## context_key = inline_script@jobs/tec_job
    ## replace_scopes = { this = planet  root = any }
    trigger = single_alias[trigger_clause]
```
Or using `context_configs_type = multiple` like

```
## context_key = inline_script@jobs/tec_job
    ## replace_scopes = { this = planet  root = any }
    ## context_configs_type = multiple
    trigger = {
        alias_name[trigger] = alias_match_left[trigger]
    }
```

But neither of these work as expected, using the single_alias, the error is as below
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/f900debe-c38b-4513-82b5-46daafbfb05a)

Using the `context_configs_type = multiple` works partially, but the scope is not pushed correctly, defaulting to any, and most scopes inside (ie going to `owner` do not change scope either)

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/ceb1fdfb-75b0-455b-8382-e37c793f4047)

**Comment by adriangaro** [comment]
Unless defining a trigger block should be done differently in the cwt configs. I also tried completely omiting the type of the parameter and just using `replace_scopes` but that didn't do it either.

**Comment by DragonKnightOfBreeze** [comment]
You should use `single_alias_right[trigger_clause]` to refer a single alias
`single_alias[x] = ...` is used to declare a single alias

But yet it's not tested, I'm not sure it's ok for `extended_config_xxx = single_alias_right[xxx]`

**Comment by adriangaro** [comment]
Tried `single_alias_right` and it seems to have same behaviour.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/564cd963-e846-4968-b0fb-2afa96982182)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/6fde33f5-f303-44c0-9970-230f4f4433f2)
