### ISSUE TITLE
push/replace_scope does not work on event targets

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#78]
Trying to declare an event target scope, it does not seem to work.
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/64af41ae-1421-4721-a084-03499366129a)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/52d4160e-5768-4013-b067-f18b44a7790f)

**Comment by DragonKnightOfBreeze** [comment]
Not supported / fully checked yet
