### ISSUE TITLE
Scope parameter that has defined type in cwt configs does not correctly switch scope if used to change scope.

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#79]
I have the following parameter, which is of type `scope[leader]` so should be able to be used as a scope, but inside the scope block, autocomplete and inference does not work.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/79975668-8a76-4a77-94e3-b02be6fa83af)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/1d79ba4d-fe56-4e99-8ad4-a99f1a22e795)

**Comment by DragonKnightOfBreeze** [comment]
Not supoorted yet

**Comment by DragonKnightOfBreeze** [comment]
Implemented in 1.3.8
