### ISSUE TITLE
Parameters are not validated when parameter is of type scope, and the value passed is of type system_link

### ISSUE THREAD

**Issue by adriangaro** [DragonKnightOfBreeze/Paradox-Language-Support#80]
`this` scope is of type `scope[leader]` (system link to current scope) yet the parameter is of type `scope[country]` in which one would expect a type error/highlight.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/5f2cd17e-9726-4feb-8d24-13dcebfa6ee6)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/99a94da4-68da-4b0b-b39c-a6264cfce7c2)

**Comment by DragonKnightOfBreeze** [comment]
This validation is drived by `IncorrectExpressionInspection` but somehow it does not work for parameter values according to the screenshot.
Could you paste necessary text snippets of scripts and cwt configs?

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/5347befa-a233-4dba-87a3-f13e36a382b5)
