### ISSUE TITLE
IntelliJ Freezes when Indexing

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#82]
Hi,

first of all I love this Plugin and your work.

But every plugin version after 1.3.12 freezes my IDE when indexing.
When I downgrade the plugin manually it works without issues.
Below are details about the issue.

IDE Version:

- IntelliJ 2024.2 (Clean new install with just this plugin)
- IntelliJ 2024.1.x (Old Install)

Plugin Settings:

- Game: 
  - Victoria 3 (Current game version 1.7.5)
  - Unsubscribed all Workshop mods
  - Removed all mods from <Documents>\Paradox Interactive\Victoria 3\mod
- Mod Projects Tested:
  - Complex mod with hundreds of files
  - [Empty mod](https://share.bahmut.de/2024-08-10_17.32.23-c85282_%25pn.zip) (Example)
    - descriptor.mod
    - .metadata/metadata.json

Behavior:

- First Load after Plugin install:
  - Project Opens as normal in IntelliJ
  - Everything works
  - Plugin starts indexing
  - Still working
  - Indexing reaches its end (according to IDE progressbar in footer)
  - IDE freezes
    - Nothing is clickable
    - IDE has high CPU usage (>10% instead of ~1%)
    - No progress after hours (Tried leaving it running for 3 hours while doing something else)
    - IDE UI does not update and turns background grey after dragging it
    - Only way to close it is via Task Manager
 - Starting the IDE after killing it before:
   - IDE freezes instantly because it wants to finish indexing
     - Same behaviour as above
 - Other Projects (e. g. Java)
   - Works as normal

Regards,

Chris

**Comment by Decent-Name-Here** [comment]
I've been having a similar issues with HOI4. Either it hangs on two specific files or just freezes midway through loading a project

other projects seem to load perfectly fine

**Comment by DragonKnightOfBreeze** [comment]
Your IDE may be reinstalled, but your IDE's cache and indices may not be invalidated, try:
1. Invalidate cache and restart
2. Produce the freeze log (when IDE freezes wait for a minute first kill second and restart 3rd, then should get the freeze log)

![image](https://github.com/user-attachments/assets/bc3de7bf-7723-4b19-897d-4c12a5af59a4)

**Comment by kaiser-chris** [comment]
Ok I had previously tried invalidating cache (forgot to mention in my inital post), but I tried it again and behaviour keeps to be the same.
Also in my test again I noticed it always seems to get stuck at the same file:
![image](https://github.com/user-attachments/assets/94b2e3c4-b206-441b-a4db-5f469666df57)
[threadDump-20240812-041001.txt](https://github.com/user-attachments/files/16576853/threadDump-20240812-041001.txt)

**Comment by DragonKnightOfBreeze** [comment]
Nothing found from above freeze logs, could thread dump log be provided when IDE is freezing? 
(use `jstack -l <pid>` command, pid of IDEA can be found in Profier tab)
![image](https://github.com/user-attachments/assets/6f663b7f-cff1-4cd1-b504-9aff06e67aee)

**Comment by DragonKnightOfBreeze** [comment]
Perhaps I should debug vic3 game directory by myself

**Comment by kaiser-chris** [comment]
@DragonKnightOfBreeze If you look at the logs you can see that _ParadoxScriptLexer is running. Also from my screenshot you can see that it is parsing [log_settings_live.json](https://github.com/user-attachments/files/16576877/log_settings_live.json) when the UI last updated. Have you tried running that file (I attached the file, from the game folder) through your lexer by hand or putting it in another game folder to see what happens? Maybe your Paradox File Lexer runs into an infinite Loop parsing a JSON file.

Should it even try to parse a JSON file using your Paradox Script Lexer? Maybe that is the issue?

**Comment by DragonKnightOfBreeze** [comment]
How about the memory have you given to IDEA? Normally, it should be 4G+ or even 8G+.
If IDEA's memory is not enough, various strange problems may be produced.

**Comment by kaiser-chris** [comment]
I have not configured any memory limit and my computer has 32gb ram

**Comment by DragonKnightOfBreeze** [comment]
Then it may be necessary to configure

**Comment by kaiser-chris** [comment]
It was 4gb. I set it to 8gb.
Same behaviour.
![image](https://github.com/user-attachments/assets/a9f1d7d1-5716-481d-a058-5aa3d050123b)

**Comment by DragonKnightOfBreeze** [comment]
> Nothing found from above freeze logs, could thread dump log be provided when IDE is freezing? (use `jstack -l <pid>` command, pid of IDEA can be found in Profier tab) ![image](https://private-user-images.githubusercontent.com/34092666/356933990-6f663b7f-cff1-4cd1-b504-9aff06e67aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODgyMjYsIm5iZiI6MTcyMzY4NzkyNiwicGF0aCI6Ii8zNDA5MjY2Ni8zNTY5MzM5OTAtNmY2NjNiN2YtY2ZmMS00Y2QxLWI1MDQtOWFmZjA2ZTY3YWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAyMTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NjdhOThhYzVhMzQ0MmNlNTIzNTUyNzVlYWI2ZDg5MjVkY2Y0NDljOTM5NzA2YTc4MDE5MzlkMjUzZmZmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WlDuk4mDfmsYYeN3UUvnopDrO8rRSx9v8PjzXtSuu5g)

Could you please provide a thread dump log by jstack when IDE is freezing?
You can follow this screenshot:
![image](https://github.com/user-attachments/assets/e3fff552-0792-44b5-bde0-7d63aee1f7c7)

**Comment by kaiser-chris** [comment]
Hi,

attached is the log:
[jstack.log](https://github.com/user-attachments/files/16624902/jstack.log)

**Comment by DragonKnightOfBreeze** [comment]
Simply typing `@@@` in a script file will cause this issue (ide freeze, infinite loop in lexer)

**Comment by DragonKnightOfBreeze** [comment]
Should be fixed in 1.3.18

**Comment by kaiser-chris** [comment]
Thank you!
