### ISSUE TITLE
Builtin Victoria 3 CWT files are Victoria 2 files

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#83]
Hi,

I am using the latest release from github (1.3.18):
![image](https://github.com/user-attachments/assets/4facfd14-da5e-4c43-94e6-ffc5fa33bc59)

For testing purposes I tried downloading [cwtools-vic3-config](https://github.com/DragonKnightOfBreeze/cwtools-vic3-config) manually and putting the config files in .config/vic3/ now the plugin properly references everything.

Seems like this script needs to be run before the next release:
https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/blob/master/cwt/scripts/clone_all.sh

Regards,

Chris

**Comment by DragonKnightOfBreeze** [comment]
Ok it's a mistake in build.gradle.kts
