### ISSUE TITLE
Simple CWT Definition not Working

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#85]
Hi,

I am again using Victoria 3 as an example but this should be reproducable with other games.

This is an example file from the base game that is defined by the CWT below:
[gbr - great britain.txt](https://github.com/user-attachments/files/16700139/gbr.-.great.britain.txt)

This the current version of the CWT file in the project of @tboby.
It does not show an error but the file above will not be highlighted and fully ignored by your plugin.
```
types = {
    type[history_country] = {
        path = "game/common/history/countries"

    }
}

history_country = single_alias_right[effect_clause]
```

This is a CWT file that was modified by me and works as expected:
```
types = {
    type[history_country] = {
        path = "game/common/history/countries"
    }
}

history_country = {
    alias_name[effect] = alias_match_left[effect]
}
```

I tried the originial CWT with the VSCode plugin by @tboby and it worked.
It seems like there is an issue with your CWT parser when the main definition does not have curly braces.

Regards,

Chris

**Comment by DragonKnightOfBreeze** [comment]
Will be resolved in 1.3.19
