### ISSUE TITLE
Date Validation and ?= does not work for Victoria 3

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#86]
Hi,

it seems like the dates of Victoria 3 can not be validated by the plugin.
Also the **?=** operator can not be used, this seems to be the same for CK3 #52.
**?=** and **=** can and are used interchangably in Victoria 3 files.

CWT for the date issue:
```
alias[effect:create_character] = {
    ...
    birth_date = date_field
    ...
}
```

Unmodified base game file with both issues:
[bad - baden.txt](https://github.com/user-attachments/files/16713907/bad.-.baden.txt)

?= Error:
![image](https://github.com/user-attachments/assets/ef653f7d-26d9-4462-b8d4-4e79cc88a741)

After changing ?= to = the date error is still there:
![image](https://github.com/user-attachments/assets/d1f7ea55-a9f2-442a-b788-c3b524ca61df)

Regards,

Chris

**Comment by DragonKnightOfBreeze** [comment]
What is `?=` meaning?

**Comment by kaiser-chris** [comment]
?= is the same as = as far as I can tell.
I can use either and the game will successfully parse the file.

**Comment by DragonKnightOfBreeze** [comment]
wtf

**Comment by kaiser-chris** [comment]
Yep!
Official files sometimes use `=` and sometimes `?=` in the same file for the same commands.
It is really strange.

**Comment by DragonKnightOfBreeze** [comment]
could `?=` be used in other situations?

**Comment by DragonKnightOfBreeze** [comment]
Strange

**Comment by kaiser-chris** [comment]
Also tested it with the VSCode Plugin of @tboby for a sanity check and it works but has strange highlighting:
![image](https://github.com/user-attachments/assets/bcf8b2c0-2f3a-4a1a-af05-9c173ca98cf7)

**Comment by DragonKnightOfBreeze** [comment]
What are the valid date formats of date fields?

**Comment by kaiser-chris** [comment]
I did some broad searches in the Victoria 3 game files and the only format I have found is this:
`birth_date = 1887.10.23`
`game_date < 1845.1.1`
`earliest_usage_date = 1841.1.1`

Format: \<year\>.\<month\>.\<day\>


If you want I could test other formats that work on other games like CK2/3 or VIC2 but VIC3 just uses the format above.

**Comment by DragonKnightOfBreeze** [comment]
OK according to all of these, the date format to validate in JVM should be `yyyy.M.d`
