### ISSUE TITLE
Stellaris - show a warning if is_triggered_only = yes is missing in an event

### ISSUE THREAD

**Issue by Inny78** [DragonKnightOfBreeze/Paradox-Language-Support#88]
is_triggered_only = yes should be present in every event, or it will fire every day with no way to stop it.
In IDEA this feature will be a new Inspection, and the name, may be NonTriggeredEventInspection.
This should only for Stellaris, check for all events, at warning level by default.

**Comment by DragonKnightOfBreeze** [comment]
Implemented in 1.3.22
