### ISSUE TITLE
Plugin inserts / to "Stellaris standard library" and attempts to scan whole hard drive

### ISSUE THREAD

**Issue by amirabiri** [DragonKnightOfBreeze/Paradox-Language-Support#90]
The plugin appears to include `/` as part of the Stellaris library on its own, and proceeds to scan for indexing the entire hard of the computer. This in turns leads (on a Mac) to multiple popups of "Intellij IDEA is asking for permissions to..." when trying to access various folders, the indexing takes forever, chokes the machine performance-wise, and creates a huge cache file.

**Comment by DragonKnightOfBreeze** [comment]
Perhaps you configured `/` as the `local config directory` in plugin settings page, or I cannot find other situations that may make plugin add `/` into roots to let IDE scanning and indexing.

**Comment by amirabiri** [comment]
I uninstalled the plugin and deleted the options...xml file, then reinstalled and it's OK now.

Still, I didn't touch the config. I suspect something happened in one of the version upgrades. Is it possible that some missing config introduced in some version got accidentally mapped to `/`? (e.g empty value --> `/`).

**Comment by DragonKnightOfBreeze** [comment]
This may happen when plugin request IDE to reparsing / reindexing, based on root paths, and the root paths contains an empty root path, I think.

**Comment by DragonKnightOfBreeze** [comment]
Will be fixed in 1.3.23
