### ISSUE TITLE
颜色问题白色背景下颜色符号看不清

### ISSUE THREAD

**Issue by Snowon-I** [DragonKnightOfBreeze/Paradox-Language-Support#92]
白色背景下颜色符号看不清
![e4ebba3ae64aef590c892d4ba74c87d1](https://github.com/user-attachments/assets/964dd1aa-0127-4d9d-8e5d-d8ef5f04209f)
![823d24fd6acfe0759fc371a89f048661](https://github.com/user-attachments/assets/5e719aa8-8bf3-4140-9774-6a633b7ca614)

**Comment by DragonKnightOfBreeze** [comment]
计划是加个配置
