### ISSUE TITLE
允许在内联脚本文件中引用其使用位置的本地封装变量 / Allow to use local scripted variables from usage locations in inline script files 

### ISSUE THREAD

**Issue by Snowon-I** [DragonKnightOfBreeze/Paradox-Language-Support#93]
内联里面引用的scripted_variable会报错（不在scripted_variable里，但是有在引用的文件最上面定义）
![7086c1fe5eb7adf472c91f0f6c91f9cc](https://github.com/user-attachments/assets/c9a2e229-9d37-4718-ae62-9cd1cc81b596)
![c163bebd469934bd1e4f4ba7b8551401](https://github.com/user-attachments/assets/206b2741-f5a7-4f81-9c1b-87923f6d9a7a)

**Comment by DragonKnightOfBreeze** [comment]
存在严重的性能问题

**Comment by DragonKnightOfBreeze** [comment]
重构了内联脚本使用的索引的实现方式，优化了性能
