### ISSUE TITLE
封装内  参数<域> 后面写码不会正常解析

### ISSUE THREAD

**Issue by Snowon-I** [DragonKnightOfBreeze/Paradox-Language-Support#95]
![4494d32717bb8d7251df28a1c1a46609](https://github.com/user-attachments/assets/66710a89-b3e1-428c-9e94-64af44ccca21)

**Comment by Snowon-I** [comment]
`MGWOIS_shroud_rifts_situation_begin = {
    start_situation = {
        target = $planet$
        type = situation_MGWOIS_shroud_rift_openning
        effect = {
            if = {
                limit = {
                    owner = {
                        OR = {
                            has_ethic = ethic_fanatic_spiritualist
                            has_ethic = ethic_spiritualist
                        }
                    }
                }
                set_situation_approach = situation_MGWOIS_full_use_the_shroud_rift_open
            }
            else_if = {
                limit = {
                    owner = {
                        has_origin = origin_MGWOIS_the_shroud_rift
                    }
                }
                set_situation_approach = situation_MGWOIS_stop_the_shroud_rift_open
            }
            else = {
                set_situation_approach = situation_MGWOIS_research_the_shroud_rift_open
            }
            add_situation_progress = $planet$.value:situation_MGWOIS_shroud_rift_open_progress_in_planet
        }
    }
    $planet$ = {
        every_owned_pop = {
            set_pop_flag = MGWOIS_pop_lock_by_shroud_rifts
        }
    }
}`

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/user-attachments/assets/24b7ebeb-68e0-4aae-ab94-d70a9ac58ee6)

**Comment by DragonKnightOfBreeze** [comment]
When merge config expressions, `alias_name[x]` and `alias_keys_field[x]` should be supported, but currently not...

`scope[effect]` vs `alias_name[effect]`

**Comment by DragonKnightOfBreeze** [comment]
![image](https://github.com/user-attachments/assets/0b65547f-5e60-4098-a71c-061d3605b512)
