### ISSUE TITLE
Support Vic3 defines

### ISSUE THREAD

**Issue by kaiser-chris** [DragonKnightOfBreeze/Paradox-Language-Support#97]
Hi,

I don't know whether other games use them like vic3 but there are defines with a Namespace and a Variable (configured in folder 'defines').
These are then referenced with the define:\<Namespace\>|\<Variable Name\>. This is done in a few vanilla locations but one notable location is in pop_types.
Below I have example code that at least allows me to link to a Namespace but I do not know how to configure the part after the pipe ( | ).

This feature seems to be missing from CWT in general.

### common/defines/00_graphics.txt (excerpt)
```
... (more code before)
NRoutes = {
	DIRTROAD_BRIDGES = { "dirtroad_bridge_01" }
	RAILROAD_1_BRIDGES = { "railroad_bridge_01" "railroad_bridge_02" }
	BRIDGE_SIZES = {
		"_small_mesh"
		"_medium_mesh"
		"_large_mesh"
		}
	ROUTE_ENTITIES_CUTOFF = 250				# zoom at which we hide all route entities
}

NPortrait = {
	GRACEFUL_AGING_START = 25	# After this age, added life expectancy will make a character look younger than they are; the effect grows the further past this point one goes
	GRACEFUL_AGING_END = 70		# This is the apparent age at which life expectancy stops slowing down visual aging (each year onwards ages you visually 1 year)
	MAX_AGE = 100.0				# At this age portraits will use the special age gene at full strength
	PORTRAIT_MALE_ADULT_AGE = 18	# The boy -> male portrait change happens at this age
	PORTRAIT_FEMALE_ADULT_AGE = 18	# The girl -> female portrait change happens at this age
}

NProvinceHighlight = {
	TEXTURE_WIDTH = 2048
	TEXTURE_HEIGHT = 1024
	# Province highlights use poisson disc sampling to create a gradient
	# Poisson disc allows for a wider sample are with fewer samples
	KERNEL_SCALE = 8	# Size of the sample area, in world space
	SAMPLE_COUNT = 16	# How many samples to use (max 16)
}
... (more code after)
```

### common/pop_types/capitalists.txt (excerpt)
```
... (more code before)
	portrait_age = {
		integer_range = {
			min = define:NPortrait|GRACEFUL_AGING_START
			max = define:NPortrait|GRACEFUL_AGING_END
		}
	}
... (more code after)
```

### common/defines.cwt
```
types = {
    type[define] = {
        path = "game/common/defines"
    }
}

define = {

}
```

### links.cwt (Excerpt)
```
... (more code before)
	define = {
		desc = " Reference the value of a numeric define: define:Namespace|Name"
		from_data = yes
		data_source = <define>
		prefix = define:
		output_scope = value
		type = value
	}
... (more code after)
```

IDE Screenshots:
![image](https://github.com/user-attachments/assets/87d5092d-2d73-4b53-81de-460485cd40eb)
![image](https://github.com/user-attachments/assets/1c943572-9127-48c7-86c2-8de7d706ed06)

**Comment by DragonKnightOfBreeze** [comment]
Maybe PLS should provide new index and more language features for define namespaces and define variables.

**Comment by DragonKnightOfBreeze** [comment]
![ddc9dac48572dab4577ddfb202ba6634](https://github.com/user-attachments/assets/4136f8ab-06a8-431a-b000-e87c5a4cfad7)

**Comment by DragonKnightOfBreeze** [comment]
Also available for code completion.

**Comment by DragonKnightOfBreeze** [comment]
@kaiser-chris remember to create pull request to plugin's vic3 config repo, with necessary `$define_reference`,thanks :)
